
services:
  wb_analyzer:
    build: .
    container_name: wb_analyzer
    ports:
      - "9005:8000"
    mem_limit: 512m
    cpus: 0.5
    restart: always
    env_file: .env
    volumes:
      - .:/app

  markets_backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: markets_backend
    ports:
      - "9006:8000"
    mem_limit: 1g
    cpus: 0.5
    restart: always
    env_file: .env
    working_dir: /workspace/backend

    depends_on:
      - db
      - redis
    volumes:
      - .:/workspace

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: markets_celery
    env_file: .env
    working_dir: /workspace/backend
    command: celery -A backend worker --loglevel=info --max-memory-per-child=500000 --concurrency=2
    mem_limit: 1gb
    cpus: 0.5
    volumes:
      - .:/workspace
    depends_on:
      - markets_backend
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping"]
      interval: 60s
      timeout: 30s
      retries: 3
  celery_beat:
      build:
        context: .
        dockerfile: docker/Dockerfile.backend
      container_name: markets_celery_beat
      env_file: .env
      working_dir: /workspace/backend
      command: celery -A backend beat --loglevel=info
      mem_limit: 256m
      cpus: 0.3
      volumes:
        - .:/workspace
      depends_on:
        - markets_backend
        - redis
        - db
      restart: always
  
  db:
    image: postgres:15
    container_name: markets_db
    restart: always
    mem_limit: 2gb
    cpus: 1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_MAX_CONNECTIONS: 100
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15433:5432"

  redis:
    image: redis:6
    container_name: markets_redis
    restart: always
    mem_limit: 256m
    cpus: 0.5
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
